[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "NCSA",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016",
]
private = { ignore = true }

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[sources]
allow-git = [
    "https://github.com/divagant-martian/rustls?rev=aee54ff6b34f2d41f85c4632082639e63a04f172"
]